package net.minedrop.auth;

import de.mkammerer.argon2.Argon2;
import de.mkammerer.argon2.Argon2Factory;
import org.slf4j.Logger;

/**
 * Argon2id password hashing for cracked-mode account security.
 * <p>
 * Uses OWASP-recommended parameters:
 * <ul>
 *   <li>Memory: 65536 KiB (64 MiB)</li>
 *   <li>Iterations: 3</li>
 *   <li>Parallelism: 2</li>
 *   <li>Salt length: 16 bytes (auto-generated by library)</li>
 *   <li>Hash length: 32 bytes</li>
 * </ul>
 * <p>
 * The Argon2 encoded output includes the salt, parameters, and hash in a
 * single string — no separate salt column needed.
 * <p>
 * <h3>Security rules:</h3>
 * <ul>
 *   <li>Never store raw passwords — only Argon2id hashes</li>
 *   <li>Never log passwords or hashes</li>
 *   <li>Clear char[] arrays after use</li>
 * </ul>
 */
public final class PasswordHasher {

    private static final int MEMORY_KIB = 65536;  // 64 MiB
    private static final int ITERATIONS = 3;
    private static final int PARALLELISM = 2;
    private static final int SALT_LENGTH = 16;
    private static final int HASH_LENGTH = 32;

    private final Argon2 argon2;
    private final Logger logger;

    public PasswordHasher(Logger logger) {
        this.argon2 = Argon2Factory.createAdvanced(
                Argon2Factory.Argon2Types.ARGON2id, SALT_LENGTH, HASH_LENGTH);
        this.logger = logger;
    }

    /**
     * Hashes a password using Argon2id.
     *
     * @param password the plaintext password (char[] — cleared after use)
     * @return the Argon2id encoded hash string (e.g., "$argon2id$v=19$m=65536,t=3,p=2$...")
     */
    public String hash(char[] password) {
        try {
            return argon2.hash(ITERATIONS, MEMORY_KIB, PARALLELISM, password);
        } catch (Exception e) {
            logger.error("Password hashing failed", e);
            return null;
        } finally {
            // Clear the password from memory
            clear(password);
        }
    }

    /**
     * Verifies a password against a stored Argon2id hash.
     *
     * @param hash     the stored Argon2id hash
     * @param password the plaintext password to verify (char[] — cleared after use)
     * @return true if the password matches
     */
    public boolean verify(String hash, char[] password) {
        if (hash == null || password == null) return false;
        try {
            return argon2.verify(hash, password);
        } catch (Exception e) {
            logger.error("Password verification error", e);
            return false;
        } finally {
            clear(password);
        }
    }

    /**
     * Checks if a hash needs upgrading (e.g., old parameters).
     * Currently always returns false — parameters are static.
     */
    public boolean needsUpgrade(String hash) {
        // Future: compare hash parameters against current settings
        return false;
    }

    /**
     * Clears a char array to prevent password lingering in memory.
     */
    private void clear(char[] data) {
        if (data != null) {
            for (int i = 0; i < data.length; i++) {
                data[i] = '\0';
            }
        }
    }

    /** Shutdown — clean up native resources. */
    public void shutdown() {
        // Argon2 instance doesn't hold persistent resources
    }
}
