// =============================================================================
// MDN-Core — Network Heartbeat (Velocity + Paper)
// =============================================================================

import java.io.File
import java.security.MessageDigest
import java.util.zip.ZipInputStream

plugins {
    `java-library`
    id("com.gradleup.shadow")
}

java {
    toolchain { languageVersion.set(JavaLanguageVersion.of(21)) }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.release.set(21)
}

dependencies {
    compileOnly("org.projectlombok:lombok:1.18.34")
    annotationProcessor("org.projectlombok:lombok:1.18.34")

    implementation(project(":mdn-api"))
    implementation(project(":mdn-bridge"))

    compileOnly("io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT")
    compileOnly("com.velocitypowered:velocity-api:3.3.0-SNAPSHOT")
    annotationProcessor("com.velocitypowered:velocity-api:3.3.0-SNAPSHOT")

    implementation("com.zaxxer:HikariCP:5.1.0")
    implementation("redis.clients:jedis:5.1.3")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
    compileOnly("org.slf4j:slf4j-api:2.0.13")  // Velocity provides SLF4J — do NOT bundle

    testImplementation(platform("org.junit:junit-bom:5.11.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.test {
    dependsOn(":mdn-bridge:shadowJar")
    useJUnitPlatform()
}

tasks.shadowJar {
    dependsOn(":mdn-bridge:shadowJar")
    archiveClassifier.set("")
    relocate("com.fasterxml", "net.minedrop.libs.jackson")
    relocate("com.zaxxer.hikari", "net.minedrop.libs.hikari")
    relocate("redis.clients.jedis", "net.minedrop.libs.jedis")
    // SLF4J NOT relocated — Velocity injects it via Guice
    // Exclude mdn-bridge classes — they're loaded from mdn-bridge.jar at runtime.
    // Bundling them creates duplicate classes across ClassLoaders, causing
    // ClassCastException: BridgePaperPlugin cannot be cast to BridgePaperPlugin.
    exclude("net/minedrop/bridge/**")
}

// Output the plain jar with a classifier so it never overwrites the shadow JAR.
// Both jar and shadowJar use archiveClassifier.set("") which targets the same
// filename; on clean builds jar runs after shadowJar and silently replaces it.
tasks.jar {
    archiveClassifier.set("original")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.build { dependsOn(tasks.shadowJar) }

tasks.processResources {
    filesMatching("plugin.yml") {
        expand(
            "pluginName" to "MDN-Core",
            "mainClass" to "net.minedrop.core.paper.CorePaperPlugin",
            "apiVersion" to "1.21",
            "version" to project.version,
            "dependsOn" to "MDN-Bridge",
            "softDependsOn" to "Vault, PlaceholderAPI, LuckPerms",
        )
    }
    // velocity-plugin.json is auto-generated by the Velocity @Plugin annotation
    // processor — no manual template needed.
}

// ── Build-time signature.json generation ──
// Computes SHA-256 of the JAR (skipping signature.json) for runtime verification.
val generateSignature by tasks.registering {
    dependsOn(tasks.jar)
    doLast {
        val sigFile = layout.buildDirectory.file("generated/signature/signature.json").get().asFile
        sigFile.parentFile.mkdirs()
        val jarFile = tasks.jar.get().archiveFile.get().asFile
        val hash = computeJarHash(jarFile)
        val json = """{"plugin_id":"mdn-core","version":"${project.version}","build_hash":"$hash","timestamp":${System.currentTimeMillis()},"gradle_build":"${project.name}"}"""
        sigFile.writeText(json)
        println("  [signature] mdn-core: $hash")
    }
}
tasks.shadowJar { dependsOn(generateSignature); from(layout.buildDirectory.dir("generated/signature")) }

// Hashes JAR by iterating ZIP entries, skipping signature.json (matches BridgeManager.computeJarHash)
fun computeJarHash(jar: File): String {
    val digest = MessageDigest.getInstance("SHA-256")
    ZipInputStream(jar.inputStream()).use { zis ->
        while (true) {
            val entry = zis.nextEntry ?: break
            if (entry.isDirectory) continue
            if (entry.name == "signature.json") continue
            digest.update(entry.name.toByteArray(Charsets.UTF_8))
            val buf = ByteArray(8192)
            var len: Int
            while (zis.read(buf).also { len = it } > 0) digest.update(buf, 0, len)
            zis.closeEntry()
        }
    }
    return digest.digest().joinToString("") { "%02x".format(it) }
}
