// =============================================================================
// MDN-Bridge — Security Foundation (Velocity + Paper)
// =============================================================================

import java.io.ByteArrayOutputStream
import java.io.File
import java.security.MessageDigest
import java.util.zip.ZipInputStream

plugins {
    `java-library`
    id("com.gradleup.shadow")
}

java {
    toolchain { languageVersion.set(JavaLanguageVersion.of(21)) }
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.release.set(21)
}

dependencies {
    compileOnly("org.projectlombok:lombok:1.18.34")
    annotationProcessor("org.projectlombok:lombok:1.18.34")

    implementation(project(":mdn-api"))

    // Jackson — required by BridgeManager's standalone ObjectMapper.
    // Declared explicitly (even though transitively reachable via mdn-api)
    // to guarantee inclusion in the shadow JAR across all build environments.
    // Jackson — required by BridgeManager's standalone ObjectMapper.
    // Declared explicitly (even though transitively reachable via mdn-api)
    // to guarantee inclusion in the shadow JAR across all build environments.
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.2")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.17.2")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.2")

    compileOnly("io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT")
    compileOnly("com.velocitypowered:velocity-api:3.3.0-SNAPSHOT")
    annotationProcessor("com.velocitypowered:velocity-api:3.3.0-SNAPSHOT")

    testImplementation(platform("org.junit:junit-bom:5.11.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.test { useJUnitPlatform() }

tasks.shadowJar {
    archiveClassifier.set("")
    relocate("com.fasterxml", "net.minedrop.libs.jackson")
    relocate("com.zaxxer.hikari", "net.minedrop.libs.hikari")
    relocate("redis.clients.jedis", "net.minedrop.libs.jedis")
}

// Output the plain jar with a classifier so it never overwrites the shadow JAR.
// Both jar and shadowJar use archiveClassifier.set("") which targets the same
// filename; on clean builds jar runs after shadowJar and silently replaces it.
tasks.jar {
    archiveClassifier.set("original")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.build { dependsOn(tasks.shadowJar) }

tasks.processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    filesMatching("plugin.yml") {
        expand(
            "pluginName" to "MDN-Bridge",
            "mainClass" to "net.minedrop.bridge.paper.BridgePaperPlugin",
            "apiVersion" to "1.21",
            "version" to project.version,
            "dependsOn" to "",
            "softDependsOn" to "",
        )
    }
    // velocity-plugin.json is auto-generated by the Velocity @Plugin annotation
    // processor — no manual template needed.
}

// ── Build-time signature.json generation ──
// Computes SHA-256 of the SHADOW JAR (skipping signature.json) for runtime verification.
// Must run AFTER shadowJar because the shadow JAR has relocated classes that change the hash.
// We compute the hash on the shadowJar, then inject signature.json back into it.
val generateSignature by tasks.registering {
    dependsOn(tasks.shadowJar)
    doLast {
        val shadowJarFile = tasks.shadowJar.get().archiveFile.get().asFile
        val hash = computeJarHash(shadowJarFile)
        val sigFile = layout.buildDirectory.file("generated/signature/signature.json").get().asFile
        sigFile.parentFile.mkdirs()
        val json = """{"plugin_id":"mdn-bridge","version":"${project.version}","build_hash":"$hash","timestamp":${System.currentTimeMillis()},"gradle_build":"${project.name}"}"""
        sigFile.writeText(json)
        // Inject signature.json using Python to preserve ZIP entry order
        project.exec {
            commandLine("python3", "-c", """
import zipfile, os
sig = '${sigFile.absolutePath}'
jar = '${shadowJarFile.absolutePath}'
with zipfile.ZipFile(jar, 'a', zipfile.ZIP_STORED) as zf:
    zf.writestr('signature.json', open(sig).read())
""".trimIndent())
        }
        println("  [signature] mdn-bridge: $hash")
    }
}
tasks.build { dependsOn(generateSignature) }

// Ensure shadowJar always triggers signature generation (even when run directly).
// This way `./gradlew :mdn-bridge:shadowJar` produces a fully signed JAR.
tasks.shadowJar { finalizedBy(generateSignature) }

// Hashes JAR by iterating ZIP entries, skipping signature.json (matches BridgeManager.computeJarHash)
// Entries are sorted alphabetically to make the hash invariant to ZIP entry order
// (which changes when signature.json is injected via jar uf).
fun computeJarHash(jar: File): String {
    val digest = MessageDigest.getInstance("SHA-256")
    val entries = mutableListOf<Pair<String, ByteArray>>()
    ZipInputStream(jar.inputStream()).use { zis ->
        while (true) {
            val entry = zis.nextEntry ?: break
            if (entry.isDirectory) continue
            if (entry.name == "signature.json") continue
            val bos = ByteArrayOutputStream()
            val buf = ByteArray(8192)
            var len: Int
            while (zis.read(buf).also { len = it } > 0) bos.write(buf, 0, len)
            zis.closeEntry()
            entries.add(entry.name to bos.toByteArray())
        }
    }
    entries.sortBy { it.first }
    for ((name, data) in entries) {
        digest.update(name.toByteArray(Charsets.UTF_8))
        digest.update(data)
    }
    return digest.digest().joinToString("") { "%02x".format(it) }
}
